<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-10-12 at 10:15:44.
 */
class MediaItemTest extends PHPUnit_Framework_TestCase
{

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers MediaItem::createMediaItem
     */
    public function testCreateMediaItem()
    {
        $mItemSeries = MediaItem::createMediaItem('/tmp/The.Big.Bang.Theory_s06e01_DIMENSION_[720p].mkv');
        $this->assertInstanceOf('MediaItemSeries', $mItemSeries);
        $mItemMovie = MediaItem::createMediaItem('/var/tmp/test.new/The.Dark.Knight.Rises-(2012)-[1080p].RELEASE.mkv');
        $this->assertInstanceOf('MediaItemMovie', $mItemMovie);

        $tvdb = TvDbMetadataManager::getInstance();
        $tvdb->fetchMediaItemData($mItemSeries);
        $this->assertNotNull($mItemSeries->posterUrl);
        
        print_r($mItemSeries);
        
        $tmdb = MovieDbMetadataManager::getInstance();
        $tmdb->fetchMediaItemData($mItemMovie);
        $this->assertNotNull($mItemMovie->posterUrl);
        
        return $mItemMovie;
    }

    /**
     * @covers MediaItem::getYear
     * @depends testCreateMediaItem
     * @param MediaItem $mediaItem
     */
    public function testGetYear($mediaItem)
    {
        $expected = '2012';
        $actual = $mediaItem->getYear();
        $this->assertEquals($expected, $actual);
    }
}
